(provide 'my-org)
(require 'org)
(require 'org-tempo)
(require 'ox-latex)

(setq org-directory "~/org/")
(setq org-agenda-files `(,(concat org-directory "agenda.org")))
(setq org-agenda-span 'month)
(setq org-export-with-toc nil)
(setq org-export-with-section-numbers nil)
(setq org-list-allow-alphabetical t)
(setq org-startup-folded 'nofold)
(setq org-hide-emphasis-markers t)
(setq org-hide-leading-stars nil)
(setq org-indent-mode-turns-on-hiding-stars nil)
(setq org-indent-mode-turns-off-adapt-indentation t)
(setq org-adapt-indentation nil)
(setq org-startup-indented t)
(setq org-pretty-entities t)
(setq org-src-tab-acts-natively t)
(setq org-src-window-setup 'other-frame)
(setq org-src-preserve-indentation t)
(setq org-todo-keywords '((sequence "TODO" "PROG" "|" "DONE" "AXED")))
(customize-set-variable 'safe-local-variable-values
                        '((org-emphasis-alist . nil)
                          (org-hide-emphasis-markers . nil)
                          (org-pretty-entities . nil)))
(add-hook 'org-mode-hook (lambda () (electric-indent-local-mode -1)))

;; (setq org-latex-compiler "pdflatex")
;; (setq org-latex-bib-compiler "biber")
(setq org-latex-pdf-process '("latexmk -pdf -bibtex %f"))
;; (setq org-agenda-files '(org-directory))
;; (setq org-agenda-file-regexp "agenda.org")
(setq org-export-backends '(ascii html latex md odt man))

(setq ispell-program-name "hunspell")
(setq ispell-local-dictionary "en_CA")
(setq ispell-local-dictionary-alist
      '(("en_CA" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil nil nil utf-8)))

(add-hook 'org-mode-hook 'auto-fill-mode)

(defun insert-zero-width-char ()
  (interactive) (insert-char #x200b))
(keymap-set org-mode-map "C-c z" 'insert-zero-width-char)
